bioSite/bioDetail/urls.py
from django.urls import path
from . import views

app_name = "bioDetail"

urlpatterns = [
    path("", views.homepage, name="homepage"),
    path("index/", views.register, name="register"),
    path("finger_image/", views.finger, name="finger"),
    path("authentic/", views.authentic, name="authentic"),
    path("not_found/", views.no_user, name="no_user"),
]

bioSite/bioSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('bioDetail.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bioSite/bioDetail/models.py
from django.db import models
from django.utils import timezone
from PIL import Image


class UserData(models.Model):
	choice = [('M', 'Male'), ('F', 'Female'), ('O', 'Other')]
	name = models.CharField(max_length=70)
	email = models.EmailField()
	gender = models.CharField(max_length=5, choices=choice, default='M')
	phone = models.IntegerField()
	address = models.TextField()
	occupation = models.CharField(max_length=100, null=True)
	organisation = models.CharField(max_length=200)
	photo = models.ImageField(upload_to='uploads/')
	date_pub = models.DateTimeField(default=timezone.now)

	def __str__(self):
		return self.name

	def save(self):
		super().save()  # saving image first

		img = Image.open(self.photo.path) # Open image using self

		if img.height > 200 or img.width > 200:
			new_img = (200, 200)
			img.thumbnail(new_img)
			img.save(self.photo.path)


class UserFingerprint(models.Model):
	user_data = models.OneToOneField(UserData, verbose_name='Users', on_delete=models.CASCADE, primary_key=True)
	finger_feature = models.JSONField()

bioSite/bioDetail/forms.py
from django import forms
from .models import UserData, UserFingerprint

class UserForm(forms.ModelForm):
	class Meta:
		model = UserData
		labels = {
			'phone': 'Phone Number',
			'photo': 'Profile Image',
			'address': 'Address',
		}
		# widgets = {
  #           'address': forms.Textarea(attrs={'class': 'form-control', 'cols':10}),
  #           'gender': forms.RadioSelect(attrs={'class': 'form-check form-check-inline'}),
  #           'name': forms.TextInput(attrs={'class': 'form-control'}),
  #           'email': forms.EmailInput(attrs={'class': 'form-control'}),
  #           'occupation': forms.TextInput(attrs={'class': 'form-control'}),
  #           'organisation': forms.TextInput(attrs={'class': 'form-control'}),
  #           'phone': forms.NumberInput(attrs={'class': 'form-control'}),
  #           'photo': forms.FileInput(attrs={'class': 'form-control'}),
  #       }
		fields = ["name", "email", "gender", "phone", "address", "occupation", "organisation", "photo"]
		

class FingerForm(forms.Form):
	f_img = forms.ImageField(label='FingerPrint Image')

bioSite/bioDetail/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import UserForm, FingerForm
from .models import UserFingerprint, UserData
from django.contrib import messages
from .model_load import *
import cv2
import numpy as np


def homepage(request):
	return render(request, 'bioDetail/home.html')

def register(request):
	if request.method == "POST":
		form = UserForm(request.POST, request.FILES)
		if form.is_valid():
			user = UserData()
			user.name = form.cleaned_data.get('name')
			user.email = form.cleaned_data.get('email')
			user.phone = form.cleaned_data.get('phone')
			user.gender = form.cleaned_data.get('gender')
			user.address = form.cleaned_data.get('address')
			user.occupation = form.cleaned_data.get('occupation')
			user.organisation = form.cleaned_data.get('organisation')
			user.photo = form.cleaned_data.get('photo')
			user.save()
			request.session['token'] = UserData.objects.latest('date_pub').pk
			print(request.session['token'])
			return redirect('bioDetail:finger')
		else:
			for msg in form.error_messages:
				messages.error(form.error_messages[msg])

	form = UserForm()
	return render(request, 'bioDetail/register.html', {'form': form})
	

def finger(request):
	if request.method == "POST":
		form = FingerForm(request.POST, request.FILES)
		if form.is_valid():
			img_path = form.cleaned_data.get('f_img').read()
			img = img_ready(img_path)
			feat = get_feature(img)
			user_d = UserData.objects.get(pk=request.session.get('token'))
			user_finger = UserFingerprint(user_data=user_d, finger_feature=feat.tolist())
			user_finger.save()
			return redirect('bioDetail:homepage')
		else:
			for msg in form.error_messages:
				messages.error(form.error_messages[msg])

	form = FingerForm()
	return render(request, 'bioDetail/finger_image.html', {'form': form})
			

def authentic(request):
	if request.method == "POST":
		form = FingerForm(request.POST, request.FILES)
		if form.is_valid():
			img_path = form.cleaned_data.get('f_img').read()
			img = img_ready(img_path)
			feat = get_feature(img)
			feat = feat.reshape(1, -1)
			user_d = UserFingerprint.objects.all()
			if user_d.exists():
				feat_d = dict()
				for u in user_d:
					feat_d[u.user_data] = np.array(u.finger_feature)
			else:
				return redirect('bioDetail:no_user')
				
			m_user = calc_dist(feat_d, feat)
			if m_user == None:
				return redirect('bioDetail:no_user')
			else:
				return render(request, 'bioDetail/users.html', {'user': m_user})
		else:
			for msg in form.error_messages:
				messages.error(form.error_messages[msg])

	form = FingerForm()
	return render(request, 'bioDetail/finger_image.html', {'form': form})


def no_user(request):
	return render(request, 'bioDetail/no_user.html')

bioSite/bioDetail/templates/bioDetail/finger_image.html
<!-- file:///home/ashish/.wine/drive_c/Program%20Files/Mantra/MFS100/MFS100ClientService/Test/MFS100ClientServiceTest.htm -->
{% extends 'bioDetail/header.html' %}
{% load static %}
{% block content %}
	<div class="form-group">
		<form method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4 white-text">Put Your Detail Here</legend>
				{{ form }}
			</fieldset>
			<br>
			<div class="form-group">
				<button class="btn btn-success btn-lg" type="submit">Next</button>
			</div>
		</form>
	</div>
	<br><br><br><br><br>
{% endblock %}

bioSite/bioDetail/templates/bioDetail/header.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Ashish Upadhyay">
	<title>Biometric Authentication</title>

	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
</head>
<body> <!-- class="bg-image" style="background-image: url('https://wallpaperaccess.com/full/1567665.png'); height: 100vh;"> -->
	
	{% include 'bioDetail/includes/navbar.html' %}

	<div>
		<div class="container">
			<br><br>
			{% block content %}{% endblock %}
		</div>
	</div>

	<footer class="footer mt-auto py-3 bg-secondary fixed-bottom">
  		<div class="container">
    		<span class="text-white">Biometric authentication site created by Ashish Upadhyay &copy;</span>
  		</div>
	</footer>

	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

</body>
</html>

bioSite/bioDetail/templates/bioDetail/home.html
{% extends 'bioDetail/header.html' %}
{% load static %}
{% block content %}
	<div class="row">
		<br><br><br>
	</div>
	<div class="row">
		<div class="col-sm-4 offset-sm-1">
			<div class="card bg-dark text-white">
  				<img src="{% static 'bioDetail/reg.jpg' %}" class="card-img">
  				<div class="card-img-overlay">
    				<h5 class="card-title"><a href="{% url 'bioDetail:register' %}" class="btn btn-success">Register<i class="bi bi-arrow-right"></i></a></h5>
  				</div>
  				<div class="card-header bg-info">Fingerprint Register</div>
  				<div class="card-body bg-info">
  					<h5 class="card-title">Register</h5>
    				<p class="card-text">Register your fingerprint with details of yours in database.</p>
  				</div>
			</div>
		</div>

		<div class="col-sm-4 offset-sm-2">
			<div class="card bg-dark text-white">
  				<img class="card-img" src="{% static 'bioDetail/auth.jpg' %}">
  				<div class="card-img-overlay">
    				<h5 class="card-title"><a href="{% url 'bioDetail:authentic' %}" class="btn btn-info">Authenticate<i class="bi bi-arrow-right"></i></a></h5> 				
    			</div>
    			<div class="card-header bg-success">Fingerprint Authenticate</div>
  				<div class="card-body bg-success">
  					<h5 class="card-title">Authenticate</h5>
    				<p class="card-text">Authenticate your fingerprint from database and get your details.</p>
  				</div>
			</div>
		</div>
	</div>
{% endblock %}

bioSite/bioDetail/templates/bioDetail/includes/navbar.html
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
   <a class="navbar-brand" href="#">Biometric Authentication</a>
   <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample01" aria-controls="navbarsExample01" aria-expanded="false" aria-label="Toggle navigation">
     <span class="navbar-toggler-icon"></span>
   </button>
   <div class="collapse navbar-collapse" id="navbarsExample01">
     <ul class="navbar-nav me-auto mb-2">
      <li class="nav-item">
        <a class="nav-link" aria-current="page" href="{% url 'bioDetail:homepage' %}"><i class="bi bi-house-fill"></i> Home</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-gear-fill"></i> Options</a>
        <ul class="dropdown-menu" aria-labelledby="dropdown01">
         <li><a class="dropdown-item" href="{% url 'bioDetail:register' %}"><i class="bi bi-person-plus-fill"></i> Register</a></li>
         <li><a class="dropdown-item" href="{% url 'bioDetail:authentic' %}"><i class="bi bi-person-check-fill"></i> Authenticate</a></li>
       </ul>
     </li>
   </ul>
 </div>
</div>
</nav>

bioSite/bioDetail/templates/bioDetail/no_user.html
{% extends 'bioDetail/header.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class="row">
	<div class="col-sm-4 col-md-8 col-lg-6">
		<p>There is not matching users. Please register yourself first.</p>
	</div>
</div>
<div class="row">
	<div class="col-md-8 col-sm-4 col-lg-4">
		<a href="{% url 'bioDetail:homepage' %}"><button class="btn btn-info">Home</button></a>
	</div>
</div>
<br><br><br><br><br>
<hr style="color: white;">
{% endblock %}

bioSite/bioDetail/templates/bioDetail/register.html
{% extends 'bioDetail/header.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class="form-group">
	<form method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		<fieldset class="form-group">
			<legend class="border-bottom mb-4 white-text">Put Your Detail Here</legend>
			{{ form|crispy }}
		</fieldset>
		<br>
		<div class="form-group">
			<button class="btn btn-success btn-lg" type="submit">Next</button>
		</div>
	</form>
</div>
<br><br><br><br><br>
<hr style="color: white;">
{% endblock %}

bioSite/bioDetail/templates/bioDetail/users.html
{% extends 'bioDetail/header.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class="row">
	<div class="col-md-3 col-lg-4">
		<img src="{{user.photo.url}}" class="img-thumbnail border-info">
	</div>
	<div class="col-md-5 col-xs-4 border border-success">
		<div>
			<br>
			<h5>Name: {{user.name}}</h5>
			<p><b>Email:</b> {{user.email}}</p>
			<p><b>Gender:</b> {{user.gender}}</p>
			<p><b>Phone No:</b> {{user.phone}}</p>
		</div>
	</div>
</div>
<div class="row border border-danger">
	<div class="col-md-8 col-lg-10">
		<p><b><u>Address:</u></b></p>
		<p>{{user.address}}</p>
	</div>
</div>
<div class="row">
	<div class="col-md-3 col-lg-3 border border-primary">
		<p><b><u>Occupation:</u></b></p>
		<p>{{user.occupation}}</p>
	</div>
	<div class="col-md-3 offset-md-1 col-lg-3 offset-lg-2 border border-secondary">
		<p><b><u>Organisation:</u></b></p>
		<p>{{user.organisation}}</p>
	</div>
</div>
<br><br><br><br><br>
<hr style="color: white;">
{% endblock %}